name: Reusable Teasting workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Testing:
    name: Reusable Teasting
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

      name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

      name: Next.js cache restore
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('./src/**/*.ts', './src/**/*.tsx') }}
        restore-keys: ${{ runner.os }}-nextjs-

      name: Install dependencies
      run: npm ci
        --omit=dev
        --prefer-offline

      name: Deduplicate dependencies
      run: npm dedupe

      name: Build project
      run: npm run build

      name: Start project
      run: npm run start &

      name: Check the application availability after a 5 seconds
      run: sleep 5s && HTTP_STATUS=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:4500/); if [[ "$HTTP_STATUS" -ne 200 ]]; then exit 1; else exit 0; fi;